In [3]:
import sys
import numpy as np

In [4]:
a=np.array(range(10))

In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = np.array([0, .5, 1, 1.5, 2])

In [7]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [8]:
a[0],a[1]

(0, 1)

In [10]:
a[::2] #chia het cho 2

array([0, 2, 4, 6, 8])

In [13]:
a[5:] #chon tu vi tri so 6

array([5, 6, 7, 8, 9])

In [15]:
a.dtype

dtype('int32')

In [16]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [17]:
A.shape

(2, 3)

In [19]:
A.ndim

2

In [20]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]

    ]
])

In [21]:
B.shape

(2, 2, 3)

In [22]:
B.ndim

3

In [25]:
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [26]:
A[1]

array([4, 5, 6])

In [27]:
A[1][0]

4

In [28]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [31]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [32]:
A[:2,2:]

array([[3],
       [6]])

In [33]:
a = np.array([1, 2, 3, 4])

In [34]:
a.sum()

10

In [35]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [36]:
A[2]

array([7, 8, 9])

In [37]:
A.sum(axis=1)

array([ 6, 15, 24])

In [38]:
A.sum(axis=0)

array([12, 15, 18])

In [39]:
A.std()

2.581988897471611

In [40]:
A.mean()

5.0