In [3]:
import sys
import numpy as np

In [4]:
a=np.array(range(10))

In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = np.array([0, .5, 1, 1.5, 2])

In [7]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [8]:
a[0],a[1]

(0, 1)

In [10]:
a[::2] #chia het cho 2

array([0, 2, 4, 6, 8])

In [13]:
a[5:] #chon tu vi tri so 6

array([5, 6, 7, 8, 9])

In [15]:
a.dtype

dtype('int32')

In [16]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [17]:
A.shape

(2, 3)

In [19]:
A.ndim

2

In [20]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]

    ]
])

In [21]:
B.shape

(2, 2, 3)

In [22]:
B.ndim

3