In [1]:
import numpy as np
import sys

In [2]:
a=np.array([2,3,4])

In [6]:
a[2],a[1]

(4, 3)

In [7]:
a[2:]

array([4])

In [8]:
a[-1]

4

In [9]:
a=np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]
])

In [11]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [13]:
a.size


9

In [14]:
a.shape

(3, 3)

In [15]:
a.sum()

27

In [16]:
a.mean()

3.0

In [17]:
a.std()

1.1547005383792515

In [18]:
a[2:,:]

array([[3, 4, 5]])

In [24]:
a[2:]

array([[3, 4, 5]])

In [37]:
a

array([0, 1, 2, 3])

In [ ]:
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])