In [1]:
import sys
import numpy as np

In [4]:
a=np.array(['a','b','c'])

In [5]:
a

array(['a', 'b', 'c'], dtype='<U1')

In [7]:
a.dtype

dtype('<U1')

In [8]:
a[1:]

array(['b', 'c'], dtype='<U1')

In [9]:
a[:-1]

array(['a', 'b'], dtype='<U1')

In [10]:
b=np.array([10,2,3])

In [11]:
b

array([10,  2,  3])

In [13]:
b.sum()

15

In [14]:
b.mean()

5.0

In [16]:
b.std()

3.559026084010437

In [17]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])

In [18]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
a[1:,:2]

array([[4, 5],
       [7, 8]])

In [28]:
a[:,1]

array([2, 5, 8])

In [29]:
a>7

array([[False, False, False],
       [False, False, False],
       [False,  True,  True]])

In [30]:
A=np.array([a>3])

In [31]:
A

array([[[False, False, False],
        [ True,  True,  True],
        [ True,  True,  True]]])