In [49]:
import numpy as np
import pandas as pd

In [53]:
a=np.array([1,2,3, np.inf,np.nan])

In [54]:
np.isinf(a)

array([False, False, False,  True, False])

In [55]:
np.isnan(a)

array([False, False, False, False,  True])

In [56]:
a[~np.isnan(a)]

array([ 1.,  2.,  3., inf])

In [57]:
a[np.isinf(a)]

array([inf])

In [58]:
df=pd.DataFrame({
    'Column A': [1, np.nan, 7],
    'Column B': [np.nan, 2, 3],
    'Column C': [np.nan, 2, np.nan]
})

In [60]:
df.isna()

Column A  Column B  Column C
0     False      True      True
1      True     False     False
2     False     False      True

In [61]:
df.isnull()

Column A  Column B  Column C
0     False      True      True
1      True     False     False
2     False     False      True

In [62]:
df.notnull()

Column A  Column B  Column C
0      True     False     False
1     False      True      True
2      True      True     False

In [64]:
pd.Series([1,2,np.nan]).sum()

3.0

In [66]:
pd.Series([np.inf, 2,4,np.nan]).mean()

inf

In [67]:
df.isnull().mean()

Column A    0.333333
Column B    0.333333
Column C    0.666667
dtype: float64

In [68]:
df[df.isna()]

Column A  Column B  Column C
0       NaN       NaN       NaN
1       NaN       NaN       NaN
2       NaN       NaN       NaN

In [69]:
s= pd.Series([1, 2, 3, np.nan, np.nan, 4])

In [70]:
s[s.notnull()]

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

In [71]:
df.dropna()

Empty DataFrame
Columns: [Column A, Column B, Column C]
Index: []

In [72]:
df.dropna(axis='columns')

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [73]:
df.dropna(how='any')

Empty DataFrame
Columns: [Column A, Column B, Column C]
Index: []

In [74]:
df.dropna(how='all')

Column A  Column B  Column C
0       1.0       NaN       NaN
1       NaN       2.0       2.0
2       7.0       3.0       NaN

In [75]:
df.fillna(method='ffill')

Column A  Column B  Column C
0       1.0       NaN       NaN
1       1.0       2.0       2.0
2       7.0       3.0       2.0

In [76]:
df.fillna(method='bfill')

Column A  Column B  Column C
0       1.0       2.0       2.0
1       7.0       2.0       2.0
2       7.0       3.0       NaN