In [1]:
import numpy as np
import pandas as pd

In [14]:
a= np.array([1,2,3, np.nan, np.inf])

In [23]:
a[~np.isnan(a)].sum()

inf

In [25]:
a[np.isinf(a)].sum()

inf

In [26]:
a[np.isinf(a)].mean()

inf

In [29]:
a[pd.isna(a[3])]

array([[ 1.,  2.,  3., nan, inf]])

In [30]:
a[pd.isnull(a)]

array([nan])

In [31]:
a[pd.notnull(a)]

array([ 1.,  2.,  3., inf])

In [ ]:
df=pd.DataFrame({
    'Column A': [1, np.nan, 7],
    'Column B': [np.nan, 2, 3],
    'Column C': [np.nan, 2, np.nan],
})
